---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: webapp
      version: v1
      color: blue
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
        version: v1
        color: blue
    spec:
      containers:
        - name: webapp
          image: ashokit/sb-logger-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  type: LoadBalancer
  selector:
    app: webapp
    version: v1
    color: blue
  ports:
    - port: 8087
      targetPort: 8080